feat: Add KeysInValidator for validating fields containing specific keys
go-goyave/goyave pull request #208
Opened 2024-06-17 22:22 UTC by bangadam

## References
Issue(s): #201 
Discussion: None

## Description
This pull request adds a new validator to the Goyave framework: KeysIn. This validator ensures that all keys in the object under validation are part of the specified parameter slice. The main benefits of this addition are:
- It provides a simple and efficient way to validate that an object contains only the allowed keys, which enhances data integrity and consistency.
- It reduces the need for custom validation logic in individual projects, promoting code reusability and maintainability.

### Possible drawbacks
- The KeysIn validator assumes that the object being validated is a map[string]interface{}. If the context value is not of this type, the validation will fail. Users need to ensure the correct data type is provided to avoid unexpected validation failures.

2024-06-18 08:06 UTC, System-Glitch requested changes
You forgot to add the default language lines in `lang/default.go`.

2024-06-18 08:06 UTC, System-Glitch commented on validation/keysin_test.go
> +func TestKeysInValidator_Validate(t *testing.T) {
Please add a test for the validator constructor (checking it's `Name()`, `IsType()`, `IsTypeDependent()` and `MessagePlaceholders()`.

2024-06-18 08:06 UTC, System-Glitch commented on validation/keysin_test.go
> +				t.Errorf("KeysInValidator.Validate() = %v, want %v", got, tt.want)
You can use `testify` for assertions.

2024-06-18 08:06 UTC, System-Glitch commented on validation/keysin.go
> +	}
This validator should check that the object doesn't contain a key that is not allowed. Here, you are checking that the object contains all the keys, which is different.

2024-06-18 08:07 UTC, System-Glitch commented
> The KeysIn validator assumes that the object being validated is a map[string]interface{}. If the context value is not of this type, the validation will fail

It is correct and this is how it should be done. 👍🏻

2024-06-18 15:31 UTC, System-Glitch commented
Implementation looks correct to me. The third test case should expect `true` instead of `false`.

2024-06-18 22:45 UTC, bangadam commented
> Implementation looks correct to me. The third test case should expect `true` instead of `false`.

updated, please check

2024-06-19 08:26 UTC, System-Glitch commented on validation/string.go
> +// KeysInValidator validates the field under validation must only contain the given keys.
```suggestion
// KeysInValidator the field under validation must be an object and all its keys must
// be equal to one of the given values.
```

2024-06-19 08:26 UTC, System-Glitch commented on validation/string.go
> +// KeysIn creates a new KeysInValidator.
```suggestion
// KeysIn the field under validation must be an object and all its keys must
// be equal to one of the given values.
```

2024-06-19 08:27 UTC, System-Glitch commented on validation/string_test.go
> +	}{
```suggestion
	cases := []struct {
		input any
		value []string
		want  bool
	}{
```

2024-06-19 08:27 UTC, System-Glitch commented on validation/string_test.go
> +		t.Run(fmt.Sprintf("Validate_%v_%t", tc.value, tc.want), func(t *testing.T) {
```suggestion
		t.Run(fmt.Sprintf("Validate_%v_%t", tc.input, tc.want), func(t *testing.T) {
```

2024-06-19 08:27 UTC, System-Glitch commented on validation/string_test.go
> +		v := KeysIn([]string{"a", "b", "c"}...)
```suggestion
		v := KeysIn("a", "b", "c")
```

2024-06-19 08:28 UTC, System-Glitch commented on validation/string_test.go
> +		{value: []string{"a", "b", "c"}, input: map[string]any{"a": 1, "b": 2}, want: true},
```suggestion
		{value: []string{"a", "b", "c"}, input: map[string]any{"a": 1, "b": 2, "c": 3}, want: true},
		{value: []string{"a", "b", "c"}, input: map[string]any{"a": 1, "b": 2, "c": 3, "d": 4}, want: false},
		{value: []string{"a", "b", "c"}, input: map[string]any{"a": 1, "b": 2}, want: true},
		{value: []string{"a", "b", "c"}, input: map[string]any{}, want: true},
		{value: []string{"a", "b", "c"}, input: "", want: false},
		{value: []string{"a", "b", "c"}, input: 'a', want: false},
		{value: []string{"a", "b", "c"}, input: 2, want: false},
		{value: []string{"a", "b", "c"}, input: 2.5, want: false},
		{value: []string{"a", "b", "c"}, input: true, want: false},
		{value: []string{"a", "b", "c"}, input: nil, want: false},
		{value: []string{"a", "b", "c"}, input: (map[string]any)(nil), want: true},
```

2024-06-21 09:08 UTC, System-Glitch approved these changes

2024-06-21 09:38 UTC, merged

2024-06-21 09:38 UTC, System-Glitch commented
Thank you very much! 🎉