Support middleware compression with Zlib, LZW, Brotli, and Zstd encoders
go-goyave/goyave pull request #220
Opened 2024-07-28 21:27 UTC by AidanKenney

Issue(s): #197, #198, #199, #200

This pull request provides new Encoders for the Goyave compress middleware using the following algorithms:
- Zlib (deflate)
- LZW
- Brotli
- Zstd

Tests and comments are included

2024-07-30 13:24 UTC, System-Glitch requested changes
Four PR in one! Thanks a lot! It just needs a few minor adjustments but otherwise it looks good to me. 👍🏻

2024-07-30 13:24 UTC, System-Glitch commented on middleware/compress/brotli.go
> +			panic(errors.New("Brotli LGWin must be either 0 or within range [10, 24]"))
Can you add a test for this please?

2024-07-30 13:24 UTC, System-Glitch commented on middleware/compress/lzw.go
> +	LitWidth int
Can you please add comments here explaining these two fields and their constraints? You can copy-paste the comments from the `compress/lzw` package. Tell `Order` is optional and its default is `lzw.LSB`.

I'm wondering if we should use a `LitWidth` of 8 as a default if it's not provided, for convenience.

2024-07-30 13:24 UTC, System-Glitch commented on middleware/compress/lzw.go
> +	return "lzw"
```suggestion
	return "compress"
```

2024-07-30 13:24 UTC, System-Glitch commented on middleware/compress/zlib.go
> +	return "zlib"
```suggestion
	return "deflate"
```

2024-07-30 13:24 UTC, System-Glitch commented on middleware/compress/zlib.go
> +// Zlib encoder for the gzip format using Go's standard `compress/gzip` package.
```suggestion
// Zlib encoder for the deflate format using Go's standard `compress/zlib` package.
```

2024-07-30 13:24 UTC, System-Glitch commented on middleware/compress/lzw.go
> +// Lzw encoder for the gzip format using Go's standard `compress/lzw` package.
```suggestion
// Lzw encoder for the compress format using Go's standard `compress/lzw` package.
```

2024-07-30 13:24 UTC, System-Glitch commented on middleware/compress/zlib.go
> +	Dict  []byte
Please add a comment explaining that this field is optional (can be `nil`).

2024-07-30 14:00 UTC, ccoVeille commented on middleware/compress/zstd_test.go
> +	reader, _ := zstd.NewReader(result.Body)
```suggestion
	reader, err := zstd.NewReader(result.Body)
	require.NoError(t, err)
```

2024-07-31 01:21 UTC, AidanKenney commented
Thanks @System-Glitch  @ccoVeille for your reviews! I think I have incorporated everything. 

Tests appears to be failing on /websocket, but I don't think these code changes are related. Please let me know if anything else is needed.

2024-07-31 07:21 UTC, System-Glitch commented
> Tests appears to be failing on /websocket
It's the db timeout plugin. It happens sometimes when the runner is a bit too busy. I'm not sure how I could make this test more consistent.

2024-07-31 10:56 UTC, System-Glitch approved these changes
LGTM

2024-07-31 10:56 UTC, System-Glitch commented on middleware/compress/brotli_test.go
> +			Quality: 12,
```suggestion
			Quality: 11,
```

2024-07-31 10:56 UTC, System-Glitch commented on middleware/compress/lzw_test.go
> +	writer := encoder.NewWriter(buf)
```suggestion
	writer := encoder.NewWriter(buf)
	assert.Equal(t, 8, encoder.LitWidth)
```

2024-07-31 14:10 UTC, merged

2024-07-31 14:10 UTC, System-Glitch commented
Merged! Thank you very much. 🎉